### PR TITLE
[bug] fix the compile error

### PR DESCRIPTION
**Pull request by carlvinhust2012**
# Proposed changes
1. fix the compile error caused by #9533 when we compile doris be.
the compile error is as follow:

/home/disk1/hugo_work/doris_dev/baidu/bdg/doris/core/be/src/exec/mysql_scan_node.cpp:140:37:   required from here
/home/disk1/hugo_work/doris_dev/baidu/bdg/doris/core/thirdparty/installed/include/fmt/core.h:1423:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1423 |       formattable<T>(),

/home/disk1/hugo_work/doris_dev/baidu/bdg/doris/core/thirdparty/installed/include/fmt/core.h:1423:7: note: 'fmt::v7::formattable<doris::TypeDescriptor>{std::integral_constant<bool, false>()}' evaluates to false
Issue Number: close #xxx

## Problem Summary:

Describe the overview of changes.

## Checklist(Required)

1. Does it affect the original behavior: (No)
3. Has unit tests been added: (No)
4. Has document been added or modified: (No)
5. Does it need to update dependencies: (No)
6. Are there any changes that cannot be rolled back: (No)

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by morningman** [comment]
The PR #9533 pass the checks, why it still cause compilation error?

**Comment by carlvinhust2012** [comment]
> The PR #9533 pass the checks, why it still cause compilation error?
I also confuse the pr 9533 how to pass the checks.
Because slot->type() just overload the operator <<, and can’t support the fmt.

**Comment by morningman** [comment]
I can do the compile without your PR. Is there any special in your env?

**Comment by carlvinhust2012** [comment]
> I can do the compile without your PR. Is there any special in your env?

no special.I just run "git pull --rebase upstream master" to update the local code.
I have a test that create a new branch from master branch with  pr9533 and it also report compile error.
after I revert the  pr9533，it can compile successfully.

**Comment by BiteTheDDDDt** [comment]
I had same problem, build fail with clang.

**Review by BiteTheDDDDt — APPROVED** [review]
LGTM
