### PR TITLE
[fix](ivm) Repair the removed rewrite-context constructor call in IvmNormalizeMTMVJoinTest

### PR DESCRIPTION
**Pull request by yujun777**
### What problem does this PR solve?

#67646 replaced `IvmRewriteContext`'s public three-argument constructor with factory methods. #67669, merged a few minutes later, added a test that still called the removed constructor, so the fe-core test sources no longer compile on master:

```
fe/fe-core/src/test/java/org/apache/doris/mtmv/ivm/IvmNormalizeMTMVJoinTest.java:1053: error:
constructor IvmRewriteContext cannot be applied to given types;
  required: (Mode, MTMV, String, boolean, ExecutionKind, Optional<IvmDryRunLimit>, Map<...>, Optional<StreamReadMode>)
  found:    (Mode, MTMV, boolean)
```

The two changes do not conflict textually, so each PR was green on its own and the breakage only showed up once both had landed.

### What is changed?

Construct the context in `testFullKeysSinkMaterializesSameNamedUnprojectedKey` through the factory the CREATE MATERIALIZED VIEW analyze flow already uses, `IvmRewriteContext.normalize(mtmv)` (see `MTMVPlanUtil`), instead of the removed constructor. Test-only change; no production code is touched.

`normalize(mtmv)` is needed here rather than `create(mtmvName)`: the test enables full keys through `mtmv.getIvmInfo().setUseFullKeys(true)`, which `IvmNormalizeMTMV.resolveUseFullKeys()` only reads on its fallback path — when the context carries a null `useFullKeys` but a non-null MTMV. `create(...)` leaves the MTMV null, which would silently resolve that setting to `false`, so the test would compile but fail. `Mode.NORMALIZE` also avoids the `Mode.INCREMENTAL` plan-signature validation, and nothing in this test asserts on the mode.

### Test

- `IvmNormalizeMTMVJoinTest` — 44 tests, 0 failures, 0 errors
- `mvn test-compile -pl fe-core -am` — BUILD SUCCESS, no errors; all fe-core test sources compile again

### CODE REVIEW

**Comment by yujun777** [comment]
run buildall

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://doris.apache.org/community/how-to-contribute/review-and-ci).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Review by hello-stephen — APPROVED** [review]
