### PR TITLE
[chore](macOS) Fix linker errors

### PR DESCRIPTION
**Pull request by adonis0147**
# Proposed changes

~~Issue Number: close #xxx~~

## Problem summary

Fix the issue introduced by #14384.

```shell
$ ./build.sh --be

Undefined symbols for architecture arm64:
  "doris::MemInfo::refresh_allocator_mem()", referenced from:
      _main in doris_main.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

```

## Checklist(Required)

1. Does it affect the original behavior: 
    - [ ] Yes
    - [x] No
    - [ ] I don't know
2. Has unit tests been added:
    - [ ] Yes
    - [ ] No
    - [x] No Need
3. Has document been added or modified:
    - [ ] Yes
    - [ ] No
    - [x] No Need
4. Does it need to update dependencies:
    - [ ] Yes
    - [x] No
5. Are there any changes that cannot be rolled back:
    - [ ] Yes (If Yes, please explain WHY)
    - [x] No

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by hello-stephen** [comment]
TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 35.5 seconds
 load time: 444 seconds
 storage size: 17150313370 Bytes
 https://doris-community-test-1308700295.cos.ap-hongkong.myqcloud.com/tmp/20221118165353_clickbench_pr_48968.html

**Comment by xinyiZzz** [comment]
@adonis0147  In `mem_info.cpp:193`, when it is __APPLE_, there is an empty `refresh_proc_meminfo`, does this not work?

**Comment by adonis0147** [comment]
> @adonis0147 In `mem_info.cpp:193`, when it is __APPLE_, there is an empty `refresh_proc_meminfo`, does this not work?

Hi @xinyiZzz , the error was caused by [be/src/service/doris_main.cpp:505](https://github.com/apache/doris/blob/master/be/src/service/doris_main.cpp#L505). This line references a function which doesn't have a definition.

**Comment by xinyiZzz** [comment]
> > @adonis0147 In `mem_info.cpp:193`, when it is __APPLE_, there is an empty `refresh_proc_meminfo`, does this not work?
> 
> Hi @xinyiZzz , the error was caused by [be/src/service/doris_main.cpp:505](https://github.com/apache/doris/blob/master/be/src/service/doris_main.cpp#L505). This line references a function which doesn't have a definition.

Thks reply @adonis0147 , I mean `refresh_proc_meminfo` defines an empty function in `mem_info.cpp:193`.
Because don't want mac to call the `refresh_allocator_mem` method.

**Comment by adonis0147** [comment]
> > > @adonis0147 In `mem_info.cpp:193`, when it is __APPLE_, there is an empty `refresh_proc_meminfo`, does this not work?
> > 
> > 
> > Hi @xinyiZzz , the error was caused by [be/src/service/doris_main.cpp:505](https://github.com/apache/doris/blob/master/be/src/service/doris_main.cpp#L505). This line references a function which doesn't have a definition.
> 
> Thks reply @adonis0147 , I mean `refresh_proc_meminfo` defines an empty function in `mem_info.cpp:193`. Because don't want mac to call the `refresh_allocator_mem` method.

It seems that `refresh_proc_meminfo` doesn't call `refresh_allocator_mem` and the implementation of `refresh_allocator_mem` just interacts with `jemalloc` or `tcmalloc` and no platform specific logic is introduced. I don't think we need to introduce a new special definition like `refresh_proc_meminfo`. More special handlings will make the maintenance job more difficult.

**Review by yiguolei — APPROVED** [review]
LGTM
