### PR TITLE
[chore](build) Fix compilation errors for BE UT

### LINKED ISSUE #23536: [Bug] Failed to build BE UT
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Some compilation errors occur when building BE UT.
```shell
ccache /devel/compiler/bin/g++ -DBE_TEST -DBOOST_DATE_TIME_NO_LIB -DBOOST_STACKTRACE_USE_BACKTRACE -DHAVE_INTTYPES_H -DHAVE_NETINET_IN_H -DUSE_HADOOP_HDFS -I/Programs/doris/be/src/apache-orc/c++/include -I/Programs/doris/be/ut_build_ASAN/src/apache-orc/c++/include -I/Programs/doris/be/ut_build_ASAN/src/clucene/src/shared -I/Programs/doris/be/src/clucene/src/core -I/Programs/doris/be/src/clucene/src/shared -I/Programs/doris/be/src/clucene/src/contribs-lib -I/Programs/doris/be/src -I/Programs/doris/be/test -I/devel/opt/java/include -I/devel/opt/java/include/linux -isystem /Programs/doris/be/../gensrc/build -isystem /Programs/doris/thirdparty/installed/include -isystem /Programs/doris/thirdparty/installed/gperftools/include -isystem /Programs/doris/thirdparty/installed/include/lz4 -isystem /Programs/doris/thirdparty/installed/include/zstd -O0 -fsanitize=address -DADDRESS_SANITIZER  -std=gnu++20   -D OS_LINUX -fno-access-control -g -Wall -Wextra -Werror -pthread -fstrict-aliasing -fno-omit-frame-pointer -Wnon-virtual-dtor -Wno-unused-parameter -Wno-sign-compare -fdiagnostics-color=always -Wno-nonnull -Wno-stringop-overread -Wno-stringop-overflow -D__STDC_FORMAT_MACROS -DBOOST_DATE_TIME_POSIX_TIME_STD_CONFIG -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX=1 -DBRPC_ENABLE_CPU_PROFILER -DS2_USE_GFLAGS -DS2_USE_GLOG -msse4.2 -DUSE_MEM_TRACKER -DUSE_UNWIND -fprofile-arcs -ftest-coverage -DGTEST_USE_OWN_TR1_TUPLE=0 -MD -MT test/CMakeFiles/doris_be_test.dir/runtime/load_stream_test.cpp.o -MF test/CMakeFiles/doris_be_test.dir/runtime/load_stream_test.cpp.o.d -o test/CMakeFiles/doris_be_test.dir/runtime/load_stream_test.cpp.o -c /Programs/doris/be/test/runtime/load_stream_test.cpp
/Programs/doris/be/test/runtime/load_stream_test.cpp: In member function 'virtual void doris::LoadStreamMgrTest::StreamService::open_stream_sink(google::protobuf::RpcController*, const doris::POpenStreamSinkRequest*, doris::POpenStreamSinkResponse*, google::protobuf::Closure*)':
/Programs/doris/be/test/runtime/load_stream_test.cpp:364:45: error: ignoring return value of 'doris::PStatus* doris::POpenStreamSinkResponse::release_status()', declared with attribute 'nodiscard' [-Werror=unused-result]
  364 |                     response->release_status();
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /Programs/doris/be/test/runtime/load_stream_test.cpp:23:
/Programs/doris/gensrc/build/gen_cpp/internal_service.pb.h:36446:26: note: declared here
36446 | inline ::doris::PStatus* POpenStreamSinkResponse::release_status() {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
/Programs/doris/be/test/runtime/load_stream_test.cpp:384:41: error: ignoring return value of 'doris::PStatus* doris::POpenStreamSinkResponse::release_status()', declared with attribute 'nodiscard' [-Werror=unused-result]
  384 |                 response->release_status();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~^~
/Programs/doris/gensrc/build/gen_cpp/internal_service.pb.h:36446:26: note: declared here
36446 | inline ::doris::PStatus* POpenStreamSinkResponse::release_status() {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
/Programs/doris/be/test/runtime/load_stream_test.cpp:392:37: error: ignoring return value of 'doris::PStatus* doris::POpenStreamSinkResponse::release_status()', declared with attribute 'nodiscard' [-Werror=unused-result]
  392 |             response->release_status();
      |             ~~~~~~~~~~~~~~~~~~~~~~~~^~
/Programs/doris/gensrc/build/gen_cpp/internal_service.pb.h:36446:26: note: declared here
36446 | inline ::doris::PStatus* POpenStreamSinkResponse::release_status() {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

### What You Expected?

Build BE UT successfully.

### How to Reproduce?

```
./run-be-ut.sh
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Issue Number: close #23536

This issue was introduced by #23414 .

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Comment by hello-stephen** [comment]
(From new machine)TeamCity pipeline, clickbench performance test result:
 the sum of best hot time: 45.41 seconds
 stream load tsv:          534 seconds loaded 74807831229 Bytes, about 133 MB/s
 stream load json:         20 seconds loaded 2358488459 Bytes, about 112 MB/s
 stream load orc:          64 seconds loaded 1101869774 Bytes, about 16 MB/s
 stream load parquet:          30 seconds loaded 861443392 Bytes, about 27 MB/s
 insert into select:          28.9 seconds inserted 10000000 Rows, about 346K ops/s
 storage size: 17162086718 Bytes

**Review by xinyiZzz — APPROVED** [review]
LGTM

**Review by yiguolei — APPROVED** [review]
LGTM
