### PR TITLE
[chore](build) Fix the build with MySQL support

### LINKED ISSUE #23018: [Bug] Failed to build BE with MySQL support
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

```shell
ld.lld: error: duplicate symbol: SHA224
>>> defined at my_sha2.cc.o:(SHA224) in archive /Programs/doris/thirdparty/installed/lib/libmysqlclient.a
>>> defined at sha256.c
>>>            sha256.o:(.text+0x4F0) in archive /Programs/doris/thirdparty/installed/lib/libcrypto.a

ld.lld: error: duplicate symbol: SHA256
>>> defined at my_sha2.cc.o:(SHA256) in archive /Programs/doris/thirdparty/installed/lib/libmysqlclient.a
>>> defined at sha256.c
>>>            sha256.o:(.text+0x580) in archive /Programs/doris/thirdparty/installed/lib/libcrypto.a

ld.lld: error: duplicate symbol: SHA384
>>> defined at my_sha2.cc.o:(SHA384) in archive /Programs/doris/thirdparty/installed/lib/libmysqlclient.a
>>> defined at sha512.c
>>>            sha512.o:(.text+0x7D0) in archive /Programs/doris/thirdparty/installed/lib/libcrypto.a

ld.lld: error: duplicate symbol: SHA512
>>> defined at my_sha2.cc.o:(SHA512) in archive /Programs/doris/thirdparty/installed/lib/libmysqlclient.a
>>> defined at sha512.c
>>>            sha512.o:(.text+0x870) in archive /Programs/doris/thirdparty/installed/lib/libcrypto.a
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

### What You Expected?

Build BE with MySQL support successfully.

### How to Reproduce?

```
WITH_MYSQL=ON ./build.sh --be --clean
```

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by adonis0147**
## Proposed changes

Issue Number: close #23018

There some linkage errors while building BE with MySQL support. This issue was introduced by #22777.

## Further comments

If this is a relatively large or complex change, kick off the discussion at [dev@doris.apache.org](mailto:dev@doris.apache.org) by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by adonis0147** [comment]
run buildall

**Review by xy720 — APPROVED** [review]
LGTM

**Comment by adonis0147** [comment]
run clickbench

**Review by yiguolei — APPROVED** [review]
LGTM
