### PR TITLE
[fix](statistics) Fix missing Mockito import in AnalysisManagerTest

### PR DESCRIPTION
**Pull request by yujun777**
### What problem does this PR solve?

Issue Number: N/A

Related PR: #62710

Problem Summary: `AnalysisManagerTest` in the `adaptive_batch_size` branch is missing the `import org.mockito.Mockito;` statement needed by the Mockito-based test methods introduced in #62686/#62710. Without this import the FE build fails at compilation with `cannot find symbol: variable Mockito`.

### Release note

None

### Check List (For Author)

- Test: No need to test (compile fix only, import statement only)
- Behavior changed: No
- Does this need documentation: No

### CODE REVIEW

**Comment by hello-stephen** [comment]
Thank you for your contribution to Apache Doris.
Don't know what should be done next? See [How to process your PR](https://cwiki.apache.org/confluence/display/DORIS/How+to+process+your+PR).

Please clearly describe your PR:
1. What problem was fixed (it's best to include specific error reporting information). How it was fixed.
2. Which behaviors were modified. What was the previous behavior, what is it now, why was it modified, and what possible impacts might there be.
3. What features were added. Why was this function added?
4. Which code was refactored and why was this part of the code refactored?
5. Which functions were optimized and what is the difference before and after the optimization?

**Comment by yujun777** [comment]
run buildall
