### PR TITLE
[fix](ut) fix BE ut compilation error

### PR DESCRIPTION
**Pull request by morningman**
followup #57181
After upgrading gtest to 1.12, need include <gtest/gtest.h>

### CODE REVIEW

**Comment by morningman** [comment]
run buildall

**Comment by hello-stephen** [comment]
# BE Regression && UT Coverage Report
Increment line coverage `100% (0/0)` :tada:

[Increment coverage report](http://coverage.selectdb-in.cc/coverage/57359_e5c663c19e51a74df22fc8557392dd3bd8ca110c_merge/increment_report/index.html)
[Complete coverage report](http://coverage.selectdb-in.cc/coverage/57359_e5c663c19e51a74df22fc8557392dd3bd8ca110c_merge/report/index.html)
| Category          | Coverage           |
|-------------------|--------------------|
| Function Coverage | 71.38% (23930/33526) |
| Line Coverage     | 57.79% (248901/430666) |
| Region Coverage   | 53.02% (206856/390171) |
| Branch Coverage   | 54.69% (88865/162486) |

**Review by hello-stephen — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]
